### ISSUE TITLE
plan price section and subsection weardly calculated if not filled

### ISSUE THREAD

**Issue by MatSarr** [elabore-coop/elabore-odoo-addons#2]
I added a section and sub section but didn't add a plan price because the amount will be calculted form articles.

The problem is that a plan price is auto added for section and subsection when a add article and save. And this plan price as no sense (I thought is was the sum quantity of article times the total amount, but not)

![image](https://user-images.githubusercontent.com/46820746/139659928-6cbb6cbc-7dab-4823-ad36-c308eb434716.png)

**Comment by stephansainleger** [comment]
This is normal: in your example, the sub-section has articles in several categories. and the plan price calculation is the average of of the plan prices of all these articles.
cf Issue https://github.com/elabore-coop/elabore-odoo-addons/issues/1 if we need to change the current calculation process.
