### ISSUE TITLE
Impossible to select budget when adding coef

### ISSUE THREAD

**Issue by MatSarr** [elabore-coop/elabore-odoo-addons#4]
I tried to add a coef (frais de chantier) to budget Test module budget.

I choosed the budget "test module budget" (which is the compta ana I reackon?)

But when I select it, the budget filed stay "budget"

![image](https://user-images.githubusercontent.com/46820746/139662167-3b5303f3-aa58-46a1-ac63-8ffcc03c7e2a.png)

**Comment by stephansainleger** [comment]
Fixed with commit https://github.com/elabore-coop/elabore-odoo-addons/commit/f02435cffa81a5c64b66e36462e67317e44b1b80
