### ISSUE TITLE
bug actual amount sum section and total

### ISSUE THREAD

**Issue by MatSarr** [elabore-coop/elabore-odoo-addons#5]
I created a vendor bill with the article "location de coffrage" and analytic account from the budget "test module budget"

The actual amount is well added for the article, but not for the subsection neither the section, or the total

![image](https://user-images.githubusercontent.com/46820746/139664175-07a96b66-2fa8-4fc6-97e4-207f504e9060.png)

![image](https://user-images.githubusercontent.com/46820746/139664197-334379ef-b486-4d6b-ba3d-edb04485a379.png)

**Comment by MatSarr** [comment]
Actually it's working now. weird. I guess I need to refresh the webpage for that?

**Comment by stephansainleger** [comment]
Or click on Refresh button maybe.
Just to clarify : if the article is not created before in the budget, when there is an invoice, it will add the article at the bottom of the budget : 
- either there is already some section / sub-section, then the article will be automatically add as child line of the last section / sub-section
- either there is no section / sub section, and the article will be alone in the table (section and sub section are not automatically generated)
