### ISSUE TITLE
timesheet are not added in actual amount 

### ISSUE THREAD

**Issue by MatSarr** [elabore-coop/elabore-odoo-addons#6]
analytic account: test module budget
project name: 2021-128
sale order: 2021-128

2 tasks have been automatically created from sale order (there are the section of the forecast)

I added timesheet for thoses 2 tasks but there not added to the actual amount of the budget

**Comment by stephansainleger** [comment]
I think the configuration is not good for the addition of the timesheets. Here are the missing steps according to me, with the timing in the costing tutorial video https://openinside1-my.sharepoint.com/:v:/g/personal/m_zahedi_open-inside_com/EYqlMExNmlRNt3OnccDC9u8B-pIWZ4AM3_lqFYOHVjUqYQ?e=n2fyTa :
- you have to create a product "Labor charge" with category Manpower (09:30)
- link the employee to the product (12:42)
Could you please check with these settings?

**Comment by MatSarr** [comment]
I didn't do that with project costing and I was working well. Cf https://docs.elabore.coop/Da8FPObVSL2JYRSnOz9YBg?both#
Moreover it's inconceivable to propose what you've written. It's to complicated. And an employee can't be linked to an unique product, it's a nonsense.

**Comment by stephansainleger** [comment]
Origin of the issue: in the original process, product_ids are not always linked to timesheet's analytic_lines. If no product is linked to the analytic line, then it is not displayed in the budget forecast.

Solution: if it exists, always add the timesheet.so_line.product_id to the corresponding analytic_line.
Delivered in commit https://github.com/elabore-coop/elabore-odoo-addons/commit/3bb7951e500ed749a69e0244b542925b7bf7cc10
